server:
  port: 8080

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: '*'
            allowedHeaders: '*'
            allowedMethods: "*"

      routes:
        - id: book-service
          uri: http://localhost:8081/
          predicates:
            - Path=/api/v1/books/**

        - id: member-service
          uri: http://localhost:8082/
          predicates:
            - Path=/api/v1/members/**